last_seed: 71296
questions:
  test1:
    q1:
      select: all
      choose: all
    q2:
      select:
      - v1
      - v2
      choose: 1
    q3:
      select: all
      choose: 2
  test2:
    q3:
      select: all
      choose: 2
    q2:
      select:
      - v1
      - v2
      - v3
      choose: 2
  test3:
    q5:
      select: all
      choose: 2
    q4:
      select:
      - v1
      - v4
      choose: all
