last_seed: 2103
mcq_layout: choices
author: "Jean-S\xE9bastien Turcotte"
title: Test - exemple
date: 12 janvier 2035 # manuel | \today | ...
questions:
  test1:
    q1:
      select: all
      choose: 2
    q2:
      select:
      - v1
      - v2
      choose: 1
    q3:
      select: all
      choose: all
      n_ans: 3
